### ISSUE TITLE
Not Working After Update to 1.10

### ISSUE THREAD

**Issue by kaismn** [AdyRock/ady.solarman#7]
The App stopped working After the Last Update. 
Sofar 2200 TL G3 Inverter

**Comment by AdyRock** [comment]
Are you using the cloud Solarman Station device or the LAN devices?

**Comment by kaismn** [comment]
I use the device over LANAm 19.04.2023 um 13:25 schrieb Adrian Rockall ***@***.***>:﻿
Are you using the cloud Solarman Station device or the LAN devices?

**Comment by AdyRock** [comment]
Could you enable the Local Log Data box, then restart the app and after a 2 minutes go back and send the log.

**Comment by MrBrickIsMe** [comment]
Hi AdyRock, until 4 days ago I had my solarman connected to Homey Pro but that stopped working. I found 2 systems in my Solarman app of which 1 was to be installed and that one was connected to homey. I could not complete that installation so I do not have data in homey. 
I reinstalled the app in Homey pro but now I cannot add a new solarman device because after login I get an invalid request error, username of password incorrect. But that is the account I login on the solarman site.
Any ideas?

In Homey I see in configure app a found inverter. So thats good. 
When selecting Summery inverter as device it says devices found but https error
Adding Solarman station I get the login but no known credentials do the trick

**Comment by AdyRock** [comment]
Have you installed the test version?

**Comment by MrBrickIsMe** [comment]
> Have you installed the test version?

V1.01. That is the only version I can find

**Comment by AdyRock** [comment]
If you add test to the end of the URL in the app store it will show you the test version 1.1.0
https://homey.app/en-gb/app/ady.solarman/Sofar--Solarman/test/
Once you have installed it you will need to repair the device.
Solarman changed the api url, so the new version has been updated to use that.

**Comment by MrBrickIsMe** [comment]
that username to use in the homey app, that is not the username for the solarman website..

**Comment by AdyRock** [comment]
Sorry, not sure I understand?
You only need the username and password for the Solarman Station device, which is a cloud device. That uses the username and password required for the Solarman website.

The inverter that is found in the Configure App screen is the local one found on the LAN via it's mDns broadcast.

**Comment by MrBrickIsMe** [comment]
On the website I change my password to a previous one. On the website I have a username for login but also e-mail and phone.
In homey I need to enter a username but I managed to login with my email and the old password... The combination e-mail and new password did not fuction so I do not know where these credentials come from.
It works now and I hope it will do so for a few months/years instead of weeks

**Comment by AdyRock** [comment]
OK, thanks for the information about the username an password. As that is all managed by Solarman, I'm not sure what they do with the information, so I guess it might be a bit of trial and error to find the combination they require when using the API.
All I have is one username and password to access everything, so i wasn't aware of different combinations.

**Comment by Northyman** [comment]
I had problems for a month or two with the solarman app, not getting contact, seemingly some problems with the api/login.

The experimental app you linked above fixed the problem! Thank you very much!
